export const translations = {
    en: {
        common: {
            back: "Back",
            back_short: "←",
            login: "Login",
            logout: "Logout",
            logout_short: "Out",
            signed_in_as: "Signed in as",
            loading: "Loading...",
            close: "Close",
            cancel: "Cancel",
            save: "Save",
            actions: "Actions",
            status: "Status",
            page: "Page",
            of: "of",
            go: "Go",
            previous: "Previous",
            prev_short: "←",
            next: "Next",
            next_short: "→",
            system: "System",
            old: "Old",
            new: "New",
            empty: "(empty)",
        },
        leaderboard: {
            title: "Leaderboard",
            short: "Board",
            subtitle: "Top contributors who help improve our term database",
            no_contributors: "No contributors yet",
            be_first: "Be the first to contribute!",
            total_edits: "Total Edits",
            total_contributors: "Total Contributors",
            rank: "Rank",
        },
        search: {
            title: "Term Search Engine",
            subtitle:
                "Search through extracted technical terms in English and Arabic",
            placeholder: "Search terms in English or Arabic...",
            found_terms: "Found {count} term{s}",
            no_results: "No terms found",
            try_adjusting: "Try adjusting your search query",
            unknown_resource: "Unknown Resource",
            added: "Added",
        },
        verify: {
            title: "Term Verification",
            status: "Term Verification",
            status_short: "Verify",
            read_only_title: "Read-Only Mode:",
            read_only_desc:
                "You are viewing this page as a guest. To edit terms or change verification status, please",
            document_preview: "Document Preview",
            loading_pdf: "Loading PDF...",
            failed_pdf: "Failed to load PDF",
            terms_on_page: "Terms on This Page",
            terms_found: "{count} term{s} found",
            no_terms_on_page: "No terms found on this page",
            english_editable: "English (Editable)",
            arabic_editable: "Arabic (Editable)",
            enter_english: "Enter English term",
            enter_arabic: "Enter Arabic term",
            accepted: "Accepted",
            rejected: "Rejected",
            pending: "Pending",
            rejection_reason: "Rejection Reason",
            rejection_desc: "Please provide a reason for rejecting this term.",
            enter_rejection_reason: "Enter rejection reason...",
            reject_term: "Reject Term",
            edit_history: "Edit History",
            no_history: "No edit history available for this term",
            english: "English",
            english_short: "EN",
            arabic: "Arabic",
            arabic_short: "AR",
        },
    },
    ar: {
        common: {
            back: "رجوع",
            back_short: "←",
            login: "تسجيل الدخول",
            logout: "تسجيل الخروج",
            logout_short: "خروج",
            signed_in_as: "تم تسجيل الدخول باسم",
            loading: "جاري التحميل...",
            close: "إغلاق",
            cancel: "إلغاء",
            save: "حفظ",
            actions: "إجراءات",
            status: "الحالة",
            page: "صفحة",
            of: "من",
            go: "اذهب",
            previous: "السابق",
            prev_short: "←",
            next: "التالي",
            next_short: "→",
            system: "النظام",
            old: "قديم",
            new: "جديد",
            empty: "(فارغ)",
        },
        leaderboard: {
            title: "لوحة المتصدرين",
            short: "المتصدرين",
            subtitle:
                "أفضل المساهمين الذين يساعدون في تحسين قاعدة بيانات المصطلحات لدينا",
            no_contributors: "لا يوجد مساهمين بعد",
            be_first: "كن أول المساهمين!",
            total_edits: "مجموع التعديلات",
            total_contributors: "إجمالي المساهمين",
            rank: "الترتيب",
        },
        search: {
            title: "محرك بحث المصطلحات",
            subtitle:
                "ابحث في المصطلحات التقنية المستخرجة باللغتين الإنجليزية والعربية",
            placeholder: "ابحث عن المصطلحات بالإنجليزية أو العربية...",
            found_terms: "تم العثور على {count} مصطلح",
            no_results: "لم يتم العثور على مصطلحات",
            try_adjusting: "حاول تعديل استعلام البحث",
            unknown_resource: "مصدر غير معروف",
            added: "أضيف",
        },
        verify: {
            title: "التحقق من المصطلحات",
            status: "التحقق من المصطلحات",
            status_short: "تحقق",
            read_only_title: "وضع القراءة فقط:",
            read_only_desc:
                "أنت تشاهد هذه الصفحة كضيف. لتعديل المصطلحات أو تغيير حالة التحقق، يرجى",
            document_preview: "معاينة المستند",
            loading_pdf: "جاري تحميل PDF...",
            failed_pdf: "فشل تحميل PDF",
            terms_on_page: "المصطلحات في هذه الصفحة",
            terms_found: "تم العثور على {count} مصطلح{s}",
            no_terms_on_page: "لا توجد مصطلحات في هذه الصفحة",
            english_editable: "الإنجليزية (قابلة للتعديل)",
            arabic_editable: "العربية (قابلة للتعديل)",
            enter_english: "أدخل المصطلح الإنجليزي",
            enter_arabic: "أدخل المصطلح العربي",
            accepted: "مقبول",
            rejected: "مرفوض",
            pending: "قيد الانتظار",
            rejection_reason: "سبب الرفض",
            rejection_desc: "يرجى تقديم سبب لرفض هذا المصطلح.",
            enter_rejection_reason: "أدخل سبب الرفض...",
            reject_term: "رفض المصطلح",
            edit_history: "سجل التعديلات",
            no_history: "لا يوجد سجل تعديلات لهذا المصطلح",
            english: "الإنجليزية",
            english_short: "EN",
            arabic: "العربية",
            arabic_short: "AR",
        },
    },
};
