export const translations = {
    en: {
        common: {
            back: "Back",
            back_short: "←",
            login: "Login",
            logout: "Logout",
            logout_short: "Out",
            signed_in_as: "Signed in as",
            loading: "Loading...",
            close: "Close",
            cancel: "Cancel",
            save: "Save",
            actions: "Actions",
            status: "Status",
            page: "Page",
            of: "of",
            go: "Go",
            previous: "Previous",
            prev_short: "←",
            next: "Next",
            next_short: "→",
            system: "System",
            old: "Old",
            new: "New",
            empty: "(empty)",
            optional: "Optional",
            clear: "Clear",
        },
        leaderboard: {
            title: "Leaderboard",
            short: "Board",
            subtitle: "Top contributors who help improve our term database",
            no_contributors: "No contributors yet",
            be_first: "Be the first to contribute!",
            total_edits: "Total Edits",
            total_contributors: "Total Contributors",
            rank: "Rank",
        },
        search: {
            title: "Term Search Engine",
            subtitle:
                "Search through extracted technical terms in English and Arabic",
            placeholder: "Search terms in English or Arabic...",
            found_terms: "Found {count} term{s}",
            no_results: "No terms found",
            try_adjusting: "Try adjusting your search query",
            unknown_resource: "Unknown Resource",
            added: "Added",
        },
        verify: {
            title: "Term Verification",
            status: "Term Verification",
            status_short: "Verify",
            read_only_title: "Read-Only Mode:",
            read_only_desc:
                "You are viewing this page as a guest. To edit terms or change verification status, please",
            document_preview: "Document Preview",
            loading_pdf: "Loading PDF...",
            failed_pdf: "Failed to load PDF",
            terms_on_page: "Terms on This Page",
            terms_found: "{count} term{s} found",
            no_terms_on_page: "No terms found on this page",
            english_editable: "English (Editable)",
            arabic_editable: "Arabic (Editable)",
            enter_english: "Enter English term",
            enter_arabic: "Enter Arabic term",
            accepted: "Accepted",
            rejected: "Rejected",
            pending: "Pending",
            rejection_reason: "Rejection Reason",
            rejection_desc: "Please provide a reason for rejecting this term.",
            enter_rejection_reason: "Enter rejection reason...",
            reject_term: "Reject Term",
            edit_history: "Edit History",
            no_history: "No edit history available for this term",
            english: "English",
            english_short: "EN",
            arabic: "Arabic",
            arabic_short: "AR",
        },
        upload: {
            title: "Upload Documents",
            description:
                "Upload PDF documents to extract technical terms in English and Arabic",
            upload_section: "Upload Document",
            upload_instructions:
                "Select a PDF file to upload and extract terms from",
            select_file: "Select PDF File",
            file_requirements: "PDF files only, max 100MB",
            page_number: "Page Number",
            page_placeholder: "e.g., 1, 2, 3...",
            page_help:
                "Optional: Specify a specific page to extract terms from",
            uploading: "Uploading",
            upload_button: "Upload Document",
            success: "Success!",
            error: "Error",
            resource_id: "Resource ID",
            how_it_works: "How It Works",
            step1_title: "Upload PDF",
            step1_desc: "Select a PDF document containing technical terms",
            step2_title: "Extract Terms",
            step2_desc: "Our AI system will extract English and Arabic terms",
            step3_title: "Review & Verify",
            step3_desc: "Browse and verify extracted terms in the database",
            tips: "Tips for Best Results",
            tip1: "Use clear, high-quality PDFs for better text extraction",
            tip2: "Documents with both English and Arabic text work best",
            tip3: "Specify page numbers for large documents to focus extraction",
            tip4: "Check the extracted terms and help verify them",
            errors: {
                invalid_type: "Please select a PDF file only",
                file_too_large: "File size exceeds 100MB limit",
                no_file: "Please select a file to upload",
                upload_failed: "Upload failed. Please try again.",
            },
        },
        check: {
            title: "Check Terms",
            subtitle: "Help us improve term accuracy by providing feedback",
            no_terms_title: "No Terms Available",
            no_terms_description:
                "There are currently no terms available for checking. Please try again later.",
            start_checking: "Start Checking",
            progress: "Progress",
            pdf_viewer: "PDF Viewer",
            image_viewer: "Image Viewer",
            view_image: "View Image",
            view_pdf: "View PDF",
            open_full_pdf: "Open Full PDF",
            no_image_available: "No image available",
            term_location: "Term Location",
            term_to_check: "Term to Check",
            review_instructions:
                "Review this term and provide feedback on whether it matches the image",
            no_english_term: "No English term",
            no_arabic_term: "No Arabic term",
            corrections: "Corrections",
            provide_feedback: "Provide Feedback",
            feedback_instructions:
                "Does this term accurately represent what you see in the image?",
            feedback_thank_you: "Thank You!",
            positive_feedback_received:
                "Your positive feedback has been recorded.",
            negative_feedback_received:
                "Your negative feedback has been recorded.",
            like: "Like",
            like_description: "Term matches the image",
            dislike: "Dislike",
            dislike_description: "Term doesn't match the image",
            feedback_anonymous:
                "Your feedback is anonymous and helps improve the system",
            previous_term: "Previous Term",
            next_term: "Next Term",
            skip_term: "Skip Term",
            about_this_term: "About This Term",
            extracted_on: "Extracted On",
            footer_note: "Want to do more than just provide feedback?",
            login_to_edit: "Login to edit terms directly",
            random_term: "Random Term",
            confidence: "Confidence",
        },
    },
    ar: {
        common: {
            back: "رجوع",
            back_short: "←",
            login: "تسجيل الدخول",
            logout: "تسجيل الخروج",
            logout_short: "خروج",
            signed_in_as: "تم تسجيل الدخول باسم",
            loading: "جاري التحميل...",
            close: "إغلاق",
            cancel: "إلغاء",
            save: "حفظ",
            actions: "إجراءات",
            status: "الحالة",
            page: "صفحة",
            of: "من",
            go: "اذهب",
            previous: "السابق",
            prev_short: "←",
            next: "التالي",
            next_short: "→",
            system: "النظام",
            old: "قديم",
            new: "جديد",
            empty: "(فارغ)",
            optional: "اختياري",
            clear: "مسح",
        },
        leaderboard: {
            title: "لوحة المتصدرين",
            short: "المتصدرين",
            subtitle:
                "أفضل المساهمين الذين يساعدون في تحسين قاعدة بيانات المصطلحات لدينا",
            no_contributors: "لا يوجد مساهمين بعد",
            be_first: "كن أول المساهمين!",
            total_edits: "مجموع التعديلات",
            total_contributors: "إجمالي المساهمين",
            rank: "الترتيب",
        },
        search: {
            title: "محرك بحث المصطلحات",
            subtitle:
                "ابحث في المصطلحات التقنية المستخرجة باللغتين الإنجليزية والعربية",
            placeholder: "ابحث عن المصطلحات بالإنجليزية أو العربية...",
            found_terms: "تم العثور على {count} مصطلح",
            no_results: "لم يتم العثور على مصطلحات",
            try_adjusting: "حاول تعديل استعلام البحث",
            unknown_resource: "مصدر غير معروف",
            added: "أضيف",
        },
        verify: {
            title: "التحقق من المصطلحات",
            status: "التحقق من المصطلحات",
            status_short: "تحقق",
            read_only_title: "وضع القراءة فقط:",
            read_only_desc:
                "أنت تشاهد هذه الصفحة كضيف. لتعديل المصطلحات أو تغيير حالة التحقق، يرجى",
            document_preview: "معاينة المستند",
            loading_pdf: "جاري تحميل PDF...",
            failed_pdf: "فشل تحميل PDF",
            terms_on_page: "المصطلحات في هذه الصفحة",
            terms_found: "تم العثور على {count} مصطلح{s}",
            no_terms_on_page: "لا توجد مصطلحات في هذه الصفحة",
            english_editable: "الإنجليزية (قابلة للتعديل)",
            arabic_editable: "العربية (قابلة للتعديل)",
            enter_english: "أدخل المصطلح الإنجليزي",
            enter_arabic: "أدخل المصطلح العربي",
            accepted: "مقبول",
            rejected: "مرفوض",
            pending: "قيد الانتظار",
            rejection_reason: "سبب الرفض",
            rejection_desc: "يرجى تقديم سبب لرفض هذا المصطلح.",
            enter_rejection_reason: "أدخل سبب الرفض...",
            reject_term: "رفض المصطلح",
            edit_history: "سجل التعديلات",
            no_history: "لا يوجد سجل تعديلات لهذا المصطلح",
            english: "الإنجليزية",
            english_short: "EN",
            arabic: "العربية",
            arabic_short: "AR",
        },
        upload: {
            title: "رفع المستندات",
            description:
                "قم برفع مستندات PDF لاستخراج المصطلحات التقنية باللغتين الإنجليزية والعربية",
            upload_section: "رفع المستند",
            upload_instructions: "حدد ملف PDF لرفعه واستخراج المصطلحات منه",
            select_file: "اختر ملف PDF",
            file_requirements: "ملفات PDF فقط، الحد الأقصى 100 ميجابايت",
            page_number: "رقم الصفحة",
            page_placeholder: "مثال: 1، 2، 3...",
            page_help: "اختياري: حدد صفحة معينة لاستخراج المصطلحات منها",
            uploading: "جاري الرفع",
            upload_button: "رفع المستند",
            success: "تم بنجاح!",
            error: "خطأ",
            resource_id: "معرف المورد",
            how_it_works: "كيف يعمل",
            step1_title: "رفع ملف PDF",
            step1_desc: "حدد مستند PDF يحتوي على مصطلحات تقنية",
            step2_title: "استخراج المصطلحات",
            step2_desc:
                "سيقوم نظام الذكاء الاصطناعي لدينا باستخراج المصطلحات الإنجليزية والعربية",
            step3_title: "المراجعة والتحقق",
            step3_desc: "تصفح وتحقق من المصطلحات المستخرجة في قاعدة البيانات",
            tips: "نصائح للحصول على أفضل النتائج",
            tip1: "استخدم ملفات PDF واضحة وعالية الجودة لاستخراج نص أفضل",
            tip2: "تعمل المستندات التي تحتوي على نص إنجليزي وعربي معًا بشكل أفضل",
            tip3: "حدد أرقام الصفحات للمستندات الكبيرة لتركيز الاستخراج",
            tip4: "تحقق من المصطلحات المستخرجة وساعد في التحقق منها",
            errors: {
                invalid_type: "يرجى اختيار ملف PDF فقط",
                file_too_large:
                    "حجم الملف يتجاوز الحد الأقصى البالغ 100 ميجابايت",
                no_file: "يرجى اختيار ملف للرفع",
                upload_failed: "فشل الرفع. يرجى المحاولة مرة أخرى.",
            },
        },
        check: {
            title: "فحص المصطلحات",
            subtitle: "ساعدنا في تحسين دقة المصطلحات من خلال تقديم الملاحظات",
            no_terms_title: "لا توجد مصطلحات متاحة",
            no_terms_description:
                "لا توجد مصطلحات متاحة للفحص حالياً. يرجى المحاولة مرة أخرى لاحقاً.",
            start_checking: "بدء الفحص",
            progress: "التقدم",
            pdf_viewer: "عارض PDF",
            image_viewer: "عارض الصور",
            view_image: "عرض الصورة",
            view_pdf: "عرض PDF",
            open_full_pdf: "فتح PDF كامل",
            no_image_available: "لا توجد صورة متاحة",
            term_location: "موقع المصطلح",
            term_to_check: "المصطلح للفحص",
            review_instructions:
                "راجع هذا المصطلح وقدم ملاحظات حول ما إذا كان يتطابق مع الصورة",
            no_english_term: "لا يوجد مصطلح إنجليزي",
            no_arabic_term: "لا يوجد مصطلح عربي",
            corrections: "التصحيحات",
            provide_feedback: "تقديم الملاحظات",
            feedback_instructions:
                "هل يمثل هذا المصطلح بدقة ما تراه في الصورة؟",
            feedback_thank_you: "شكراً لك!",
            positive_feedback_received: "تم تسجيل ملاحظاتك الإيجابية.",
            negative_feedback_received: "تم تسجيل ملاحظاتك السلبية.",
            like: "إعجاب",
            like_description: "المصطلح يتطابق مع الصورة",
            dislike: "عدم إعجاب",
            dislike_description: "المصطلح لا يتطابق مع الصورة",
            feedback_anonymous: "ملاحظاتك مجهولة وتساعد في تحسين النظام",
            previous_term: "المصطلح السابق",
            next_term: "المصطلح التالي",
            skip_term: "تخطي المصطلح",
            about_this_term: "حول هذا المصطلح",
            extracted_on: "تم الاستخراج في",
            footer_note: "هل تريد أن تفعل أكثر من مجرد تقديم الملاحظات؟",
            login_to_edit: "سجل الدخول لتعديل المصطلحات مباشرة",
            random_term: "مصطلح عشوائي",
            confidence: "الثقة",
        },
    },
};
